####menu
####菜单栏
menu:
  Home: /
  Archives: /archives
  About: /about

####widgets
####插件
widgets:
- search
- category
- tagcloud
- links
## provide seven widgets:search,category,tagcloud,tag,weibo,recent_comments,links
## 提供7个插件：搜索，分类，标签，标签云，微博秀，最新评论，友情链接。

duoshuo_enable: true	##不想用，改为false即可
duoshuo_shortname: hellc    ##你的多说shortname，上面为true，这个才会起效果
##duoshuo comments's shortname
##多说评论的shortname

tencent_sid: 44218032
##tencent analysis
##腾讯分析sid

baidu_sid: 7192fa361f5cabb11d8a22de41c1ba8f
##baidu statistics id
##百度统计sid，该sid为百度统计代码中：hm.src = "//hm.baidu.com/hm.js?之后的一串字符

excerpt_link: Read more

twitter:
  username:
  show_replies: false
  tweet_count: 5

#### Fancybox,图片效果插件。
fancybox: true

google_analytics: 

#### RSS 
rss: /atom.xml
## RSS address.

#### Image
#### 图片
imglogo:
  enable: true              ## display image logo true/false.是否开启网站的logo，标题左边的logo。
  src: imgs/HellcLogo.jpg        ## `.svg` and `.png` are recommended,please put image into the theme folder `/concise/source/imgs`.图片放在`/concise/source/imgs`目录下,使用.svg和.png格式的图片.
favicon: imgs/HellcFavicon.ico   ## size:32px*32px,`.ico` is recommended,please put image into the theme folder `/concise/source/imgs`. 书签图标,放在`/concise/source/imgs`下.
    
author_img_enable: true		## the picture of the lower left corner.是否开启作者头像
author_img: imgs/HellcLogo.jpg ## the path of the author_img.作者头像的路径,以../comcise/source/文件夹为根路径,如果放在imgs文件夹下,格式如本人范例


#### Author information
#### 作者信息,在博客右下角显示的小图标链接。
author:
  google_plus:    ## eg:116338260303228776998 for https://plus.google.com/u/0/116338260303228776998
  intro_line1: "Hi, I'm Hellc, an OIer of SDOI. ^_^"
  intro_line2: "Welcome To My Blog!"
  weibo:      ## e.g. 436062867 for http://weibo.com/436062867
  twitter:    ## e.g. yangjiansky for https://twitter.com/yangjiansky
  github: 5261    ## e.g. A-limon for https://github.com/A-limon
  facebook: 
  tsina:      ## e.g. 1664838973  Your weibo ID,It will be used in share button.
  linkedin:   ## e.g. in/jeffweiner08 for https://www.linkedin.com/in/jeffweiner08
  email: 


  

